### ISSUE TITLE
Is the font too big? 

### ISSUE THREAD

**Issue by starbelly** [tsloughter/rebar3.org#12]
On my screen the font is too big, is it just me? Should we adjust the style?

**Comment by ferd** [comment]
It does seem a bit big to me as well, though the old site sometimes got complaints for being a bit hard to read in terms of size and contrast.

**Comment by starbelly** [comment]
Yeah, I feel it's too small on the production site. It's defined in `px` though vs `em` or percentage. I think if we find a happy medium defining the font size in em or percentage that'll work pretty well for most people. Likewise, we can also define different base font sizes depending on the user's media width.

**Comment by starbelly** [comment]
<img width="1011" alt="Screen Shot 2020-07-13 at 4 59 31 PM" src="https://user-images.githubusercontent.com/39971740/87357842-5430bd00-c52a-11ea-9115-49ef3a55e06a.png">
☝️ default base font size (1rem) 

👇 Adjusted to 0.9rem

<img width="981" alt="Screen Shot 2020-07-13 at 4 59 50 PM" src="https://user-images.githubusercontent.com/39971740/87357888-6a3e7d80-c52a-11ea-8165-db7cd6e20a5f.png">

**Comment by starbelly** [comment]
@ferd @tsloughter How do you feel about the size up above?

**Comment by ferd** [comment]
The images are auto-resized by github and when I open them they seem to be a HDPI/retina kind of screenshot so I have no idea how they actually apply to the real world. That being said, in github the new font looks too small, auto-resized in my browser (which has a wider viewport) the smaller font looks good, and in full screen they're both too large because of the resolution.

**Comment by starbelly** [comment]
Aight, PR coming up. It's a one liner.
